version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

networks:
  human-detection-network:
    driver: bridge
  